# Generated by Django 4.1.6 on 2023-02-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('destinations', models.CharField(max_length=300)),
                ('days', models.CharField(choices=[('day', 'day'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30)),
                ('nights', models.CharField(choices=[('night', 'night'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30)),
                ('stay', models.CharField(choices=[('stay', 'stay'), ('3star', '3star'), ('4star', '4star'), ('5star', '5star'), ('resort', 'resort'), ('treehut', 'treehut')], max_length=30)),
                ('pet', models.CharField(choices=[('pets', 'pets'), ('pyes', 'pyes'), ('pno', 'pno')], max_length=30)),
                ('food', models.CharField(choices=[('foods', 'foods'), ('fyes', 'fyes'), ('fno', 'fno')], max_length=30)),
                ('rate', models.CharField(max_length=30)),
            ],
        ),
    ]
