# Generated by Django 4.1.6 on 2023-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0002_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='days',
            field=models.IntegerField(choices=[('day', 'day'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')]),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='nights',
            field=models.IntegerField(choices=[('night', 'night'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')]),
        ),
    ]
