# Generated by Django 4.1.6 on 2023-02-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0005_alter_uploadmodel_days_alter_uploadmodel_nights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='days',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='uploadmodel',
            name='nights',
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='destina',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadmodel',
            name='duration',
            field=models.CharField(choices=[('0-0', '0-0'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='agency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='food',
            field=models.CharField(choices=[('food', 'food'), ('fyes', 'fyes'), ('fno', 'fno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='pet',
            field=models.CharField(choices=[('pet', 'pet'), ('pyes', 'pyes'), ('pno', 'pno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='stay',
            field=models.CharField(max_length=20),
        ),
    ]
