# Generated by Django 4.1.6 on 2023-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0006_remove_uploadmodel_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='food',
            field=models.CharField(choices=[('food', 'food'), ('yes', 'yes'), ('no', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='pet',
            field=models.CharField(choices=[('pet', 'pet'), ('yes', 'yes'), ('no', 'no')], max_length=20),
        ),
    ]
