# Generated by Django 4.1.6 on 2023-02-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0008_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('destina', models.CharField(max_length=20, null=True)),
                ('food', models.CharField(max_length=20)),
                ('pet', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('stay', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=20)),
            ],
        ),
    ]
