# Generated by Django 4.1.6 on 2023-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0009_wishmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='destina',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='duration',
            field=models.CharField(choices=[('0-0', '0-0'), ('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8'), ('8-9', '8-9'), ('9-10', '9-10')], max_length=20),
        ),
    ]
