# Generated by Django 4.1.6 on 2023-02-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0010_alter_uploadmodel_destina_alter_uploadmodel_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadmodel',
            new_name='packageuploadmodel',
        ),
    ]
