# Generated by Django 4.1.6 on 2023-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0011_rename_uploadmodel_packageuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='destina',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='packageuploadmodel',
            name='destina',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='wishmodel',
            name='destina',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
