# Generated by Django 4.1.6 on 2023-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvoyage', '0012_alter_bookmodel_destina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='placemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
    ]
